project_Doniraj/faza5/Doniraj/Doniraj/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

#Author:Marija Stakic 2021/0320

urlpatterns = [
    path('admin/', admin.site.urls),

    path('organizacije/', views.organizacije, name='organizacije'),
    path('organizacijaProfil/', views.organizacijaProfil),
    path('organizacijaOglas/<int:organization_id>/', views.organizacijaOglas, name='organizacijaOglas'),

    path('inbox/', views.inbox),
    path('chat/', include('chat.urls')),
   

    path('users/',include('users.urls')),

    path('', RedirectView.as_view(url='/oglasi/', permanent=True)),
    path('oglasi/', include('oglasi.urls')),  


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_Doniraj/faza5/Doniraj/chat/urls.py
from django.urls import path
from .views import *
#Autor: Stasa Zujkovic 2021/0321
app_name = 'chat'

urlpatterns = [
    path('', chat_view, name="home"),
    path('chat/<username>', get_or_create_chatroom, name="start-chat"),
    path('chatroom/<chatroom_name>', chat_view, name="chatroom"),
    
]

project_Doniraj/faza5/Doniraj/oglasi/urls.py
from django.urls import path
from . import views
#Autor: Lazar Krpovic 2021/0633
app_name = 'oglasi'

urlpatterns = [
    path('', views.pocetna , name="home"),
    path('oglas/<int:oglas_id>/', views.oglas, name='oglas'),
    path('fetch_oglases/', views.fetch_oglases, name='fetch_oglases'),
    path('postaviOglas/', views.postaviOglas, name = "postaviOglas"),
    path('search/', views.search, name='search'),
    path('delete_oglas/<int:oglas_id>/', views.deleteOglas, name = "deleteOglas"),
]

project_Doniraj/faza5/Doniraj/users/urls.py
#Autor: Matija Milic 2021/0088
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('registracija/',views.registracija, name = "registracija"),
    path('logovanje/',views.logovanje, name = "logovanje"),
    path('logout/',views.logout_view, name = "logout"),
    path('nalozi/',views.nalozi, name = "nalozi"),
    path('zahtevi/',views.zahtevi, name = "zahtevi"),
    path('zahtev/<int:id>/', views.zahtev, name='zahtev'),
    path('zahtev/<int:id>/approve/', views.approve_zahtev, name='approve_zahtev'),
    path('zahtev/<int:id>/reject/', views.reject_zahtev, name='reject_zahtev'),
    path('promenaLozinke/', views.promenaLozinke, name='promenaLozinke'),
    path('promenaSlike/', views.promenaSlike, name='promenaSlike'),
    path('delete_account/<int:user_id>/', views.delete_account, name='delete_account'),
    
    path('milica/<int:id>', views.milica, name = "milica"),

    path('zaboravljenaLozinka/', views.zaboravljenaLozinka, name = "zaboravljenaLozinka"),
    path('code_verify/', views.codeVerify, name='code_verify'),
    path('password_reset/', views.passwordReset, name='password_reset'),
]

project_Doniraj/faza5/Doniraj/oglasi/models.py
from django.db import models

# Create your models here.

from users.models import User
#Autor: Lazar Krpovic 2021/0633

class Tag(models.Model):
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag

class Oglas(models.Model):
    POL_CHOICES = (
        ('musko' , 'musko'),
        ('zensko' , 'zensko'),
        ('decije', 'decije'),
    )
    VELICINA_CHOICES = (
        ('bebe' , 'bebe'),
        ('xs' , 'XS'),
        ('s' , 'S'),
        ('m' , 'M'),
        ('l' , 'L'),
        ('xl' , 'XL'),
        ('xxl' , 'XXL'),

    )
    

    naziv = models.CharField(max_length=255)
    stanje = models.IntegerField()
    opis = models.TextField()
    korisnik = models.ForeignKey(User, on_delete=models.CASCADE)
    pol = models.CharField(max_length=6, choices=POL_CHOICES)
    velicina = models.CharField(max_length=5, choices = VELICINA_CHOICES)
    vreme = models.DateTimeField(auto_now_add=True)
    slika = models.ImageField(upload_to='oglasi/')
    tagovi = models.ManyToManyField(Tag, through='Sadrzi')

    def __str__(self):
        return self.naziv

class Sadrzi(models.Model):
    oglas = models.ForeignKey(Oglas, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.oglas.naziv} - {self.tag.tag}"

project_Doniraj/faza5/Doniraj/oglasi/forms.py
#Autor: Lazar Krpovic 2021/0633
from django import forms
from .models import Oglas

class OglasForm(forms.ModelForm):

    VELICINA_CHOICES = [
        ('bebe', 'Bebe'),
        ('xs', 'XS'),
        ('s', 'S'),
        ('m', 'M'),
        ('l', 'L'),
        ('xl', 'XL'),
        ('xxl', 'XXL')
    ]
    
    POL_CHOICES = [
        ('musko', 'Muškarci'),
        ('zensko', 'Žene'),
        ('decije', 'Deca')
    ]
    
    velicina = forms.ChoiceField(
        choices= VELICINA_CHOICES,
        widget=forms.Select(attrs={'id': 'velicina'})
    )

    pol = forms.ChoiceField(
        choices= POL_CHOICES,
        widget=forms.Select(attrs={'id': 'pol'})
    )
    tagovi = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Unesite tagove odvojene razmakom', 'style': 'width: 400px;'}))

    class Meta:
        model = Oglas
        fields = ['naziv', 'stanje', 'opis', 'pol', 'velicina', 'slika', 'tagovi']
        widgets = {
            
            'naziv': forms.TextInput(attrs={'id': 'naziv'}),
            'stanje': forms.NumberInput(attrs={'id': 'stanje', 'min': 1, 'max': 5}),
            
            'opis': forms.Textarea(attrs={'id': 'opis', 'rows': 4, 'cols': 50}),
            'slika': forms.ClearableFileInput(attrs={'id': 'slika'}),
        }

project_Doniraj/faza5/Doniraj/oglasi/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import OglasForm
from .models import Oglas, Tag, Sadrzi
from django.contrib.auth.decorators import login_required
# Create your views here.
#Autor: Matija Milic 2021/0088 ,Lazar Krpovic 2021/0633

def fetch_oglases(request):
    if request.method == 'GET':
        oglasi = Oglas.objects.all()
        oglasi_list = [
            {
                'id': oglas.id,
                'naziv': oglas.naziv,
                'opis': oglas.opis,
                'slika_url': request.build_absolute_uri(oglas.slika.url)  # Construct the full URL for the image
            } for oglas in oglasi
        ]
        return JsonResponse({'oglasi': oglasi_list})


def pocetna(request):
    oglasi = Oglas.objects.all()
    return render(request, 'oglasi/pocetna.html', {'oglasi': oglasi})

def oglas(request, oglas_id):
    oglas = get_object_or_404(Oglas, pk=oglas_id)
    return render(request, 'oglasi/oglas.html', {'oglas': oglas})


def postaviOglas(request):
    if request.method == "POST":
        form = OglasForm(request.POST, request.FILES)
        if form.is_valid():
            oglas = form.save(commit=False)
            oglas.korisnik = request.user  
            oglas.save()
            
            tags_str = form.cleaned_data['tagovi']
            tags_list = [tag.strip() for tag in tags_str.split(' ')]
            for tag_name in tags_list:
                tag, created = Tag.objects.get_or_create(tag=tag_name)
                Sadrzi.objects.create(oglas=oglas, tag=tag)
            
            return redirect('oglasi:home')  
    else:
        form = OglasForm()
    
    return render(request, 'oglasi/postaviOglas.html', {'form': form})

#AJAX poziv za pretragu kada se submituje search forma
def search(request):
    query = request.GET.get('q', '')
    words = query.split()
    velicina = request.GET.get('velicina', '')
    pol = request.GET.get('pol', '')

    oglasi = Oglas.objects.all()

    if velicina != 'null':
        oglasi = oglasi.filter(velicina=velicina)
    if pol != 'null':
        oglasi = oglasi.filter(pol=pol)

    if query:
        for word in words:
            oglasi_by_name = oglasi.filter(naziv__icontains=word)
            oglasi_by_tag = oglasi.filter(tagovi__tag__icontains=word)
            oglasi = (oglasi_by_name | oglasi_by_tag).distinct()

    oglasi_list = [
        {
            'id': oglas.id,
            'naziv': oglas.naziv,
            'opis': oglas.opis,
            'slika_url': oglas.slika.url
        }
        for oglas in oglasi
    ]
    return JsonResponse({'oglasi': oglasi_list})


def deleteOglas(request, oglas_id):
    if request.method == 'POST':
        oglas = get_object_or_404(Oglas, id=oglas_id)
        nizSadrzi = Sadrzi.objects.filter(oglas = oglas)
        tagovi = [sadrzi.tag for sadrzi in nizSadrzi]
        oglas.delete()
       
        for tag in tagovi:
            SadrziNiz = Sadrzi.objects.filter(tag = tag)
            if not SadrziNiz:
                tag.delete()


        return JsonResponse({'status': 'success', 'message': 'Oglas obrisan.'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'}, status=400)

    

project_Doniraj/faza5/Doniraj/oglasi/templates/oglasi/adminProfil.html
<!--Marija Stakic 2021/0320-->
{% extends 'layout.html' %}

{% block title %}
    Admin profil
{% endblock %}

{% block content %}

<h1> Admin profil </h1>

{% endblock %}

project_Doniraj/faza5/Doniraj/oglasi/templates/oglasi/oglas.html
<!--Marija Stakic 2021/0320-->
{% extends 'layout.html' %}

{% block title %}
    Oglas
{% endblock %}

{% block content %}

<div class="proizvod">
    <div class="slika">
        <img src="{{ oglas.slika.url }}" alt="Proizvod" id="proizvod" width="500px">  
    </div>
    <div class="tekst">
        <h2>{{ oglas.naziv }}</h2>   
        <p>{{ oglas.opis }}<br> {{ oglas.pol }}, {{ oglas.velicina }}, stanje: {{ oglas.stanje }}/5</p>  
        <div class="row align-items-center">
            <div class="col-auto marg profilna">
                <a href="{% url 'users:milica' oglas.korisnik.id %}">
                    <img src="{{ oglas.korisnik.image.url }}" alt="Profilna slika" class="manjaProfilna rounded-circle border border-dark mb-2"> 
                </a>
                <p class="mb-1">@{{ oglas.korisnik.username }}</p>
                <p class="mb-1 link-secondary">{{ oglas.korisnik.oglas_set.count }} oglasa</p>
                <a href="{% url 'chat:start-chat' oglas.korisnik.username %}" class="link-secondary">
                    <img src="/media/images/chat.png" alt="chat" width="25px">
                    Kontaktiraj
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

project_Doniraj/faza5/Doniraj/oglasi/templates/oglasi/pocetna.html
<!--Autori: Marija Stakic 2021/0320, Matija Milic 2021/0088-->
{% extends 'layout.html' %}

{% block title %}
    Pocetna
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <span class="nav-link link-dark">Pol:</span>
                <select class="form-select" aria-label="Pol" name="pol" id="pol-select">
                    <option selected  value = "null">...</option>
                    <option value="decije">Deca</option>
                    <option value="musko">Muškarci</option>
                    <option value="zensko">Žene</option>
                </select>
                <span class="nav-link link-dark">Veličina:</span>
                <select class="form-select" aria-label="Veličina" id="velicina-select" name="velicina">
                    <option selected value = "null">...</option>
                    <option value="xs">XS</option>
                    <option value="s">S</option>
                    <option value="m">M</option>
                    <option value="l">L</option>
                    <option value="xl">XL</option>
                </select>
            </div>
        </div>
    </div>
</nav>

<div class="container mt-4">
    <div class="row justify-content-start" id="results-container">
        {% for oglas in oglasi %}
            <div class="col-md-6 col-sm-12 col-lg-4 col-xl-3 mb-4">
                <div class="card same-height-card" style="width: 18rem;" name="kartica">
                    <a href="/oglasi/oglas/{{ oglas.id }}">
                        <div class="text-center">
                            <img src="{{ oglas.slika.url }}" class="card-img-top img-fluid" alt="{{ oglas.naziv }}">
                        </div>
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ oglas.naziv }}</h5>
                        <p class="card-text">{{ oglas.opis }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const searchForm = document.getElementById('search-form');
        const searchInput = document.getElementById('search-input');
        const velicinaSelect = document.getElementById('velicina-select');
        const polSelect = document.getElementById('pol-select');
        const resultsContainer = document.getElementById('results-container');
    
        searchForm.addEventListener('submit', function(event) {
            event.preventDefault();
            const query = searchInput.value;
            const velicina = velicinaSelect.value;
            const pol = polSelect.value;
    
            fetch(`/oglasi/search/?q=${query}&velicina=${velicina}&pol=${pol}`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest',
                }
            })
            .then(response => response.json())
            .then(data => {
                const oglasi = data.oglasi;
                resultsContainer.innerHTML = '';
                oglasi.forEach(oglas => {
                    const card = document.createElement('div');
                    card.className = 'col-md-6 col-sm-12 col-lg-4 col-xl-3 mb-4';
                    card.innerHTML = `
                        <div class="card same-height-card" style="width: 18rem;" name="kartica">
                            <a href="/oglasi/oglas/${oglas.id}">
                                <div class="text-center">
                                    <img src="${oglas.slika_url}" class="card-img-top img-fluid" alt="${oglas.naziv}">
                                </div>
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">${oglas.naziv}</h5>
                                <p class="card-text">${oglas.opis}</p>
                            </div>
                        </div>
                    `;
                    resultsContainer.appendChild(card);
                });
            })
            .catch(error => console.error('Error:', error));
        });
    });

    function ajax(){
        const resultsContainer = document.getElementById('results-container');
        fetch(`fetch_oglases`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest',
            }
        }).then(response => response.json())
        .then(data => {
            const oglasi = data.oglasi;
            resultsContainer.innerHTML = '';
            oglasi.forEach(oglas => {
                const card = document.createElement('div');
                card.className = 'col-md-6 col-sm-12 col-lg-4 col-xl-3 mb-4';
                card.innerHTML = `
                    <div class="card same-height-card" style="width: 18rem;" name="kartica">
                        <a href="/oglasi/oglas/${oglas.id}">
                            <div class="text-center">
                                <img src="${oglas.slika_url}" class="card-img-top img-fluid" alt="${oglas.naziv}">
                            </div>
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">${oglas.naziv}</h5>
                            <p class="card-text">${oglas.opis}</p>
                        </div>
                    </div>
                `;
                resultsContainer.appendChild(card);
            });
        })
        .catch(error => console.error('Error:', error));
    }

    setInterval(ajax, 2000);
</script>


{% endblock %}

project_Doniraj/faza5/Doniraj/oglasi/templates/oglasi/postaviOglas.html
<!--#Autor: Lazar Krpovic 2021/0633-->
{% extends 'layout.html' %}

{% block title %}
    Postavi Oglas
{% endblock %}

{% block content %}

<h2 class="levo">Forma za pravljenje oglasa</h2>
<div class="d-flex justify-content-center align-items-center marg">
  <form id="oglasForma" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}
      
      <div>
          <label for="{{ form.naziv.id_for_label }}">Naziv proizvoda:</label><br>
          {{ form.naziv }}
          {{ form.naziv.errors }}
      </div><br><br>

      <div>
          <label for="{{ form.velicina.id_for_label }}">Veličina:</label><br>
          {{ form.velicina }}
          {{ form.velicina.errors }}
      </div><br><br>

      <div>
          <label for="{{ form.stanje.id_for_label }}">Stanje:</label><br>
          {{ form.stanje }}
          {{ form.stanje.errors }}
      </div><br><br>

      <div>
          <label for="{{ form.pol.id_for_label }}">Pol:</label><br>
          {{ form.pol }}
          {{ form.pol.errors }}
      </div><br><br>

      <div>
          <label for="{{ form.tagovi.id_for_label }}">Tagovi:</label><br>
          {{ form.tagovi }}
          {{ form.tagovi.errors }}
      </div><br><br>

      <div>
          <label for="{{ form.opis.id_for_label }}">Opis:</label><br>
          {{ form.opis }}
          {{ form.opis.errors }}
      </div><br><br>

      <div>
          <label for="{{ form.slika.id_for_label }}">Slika:</label><br>
          {{ form.slika }}
          {{ form.slika.errors }}
      </div><br><br>

      <input type="submit" class="btn btn-danger" value="Objavi oglas">
  </form>
</div>

{% endblock %}