project_Doniraj/faza5/Doniraj/Doniraj/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

#Author:Marija Stakic 2021/0320

urlpatterns = [
    path('admin/', admin.site.urls),

    path('organizacije/', views.organizacije, name='organizacije'),
    path('organizacijaProfil/', views.organizacijaProfil),
    path('organizacijaOglas/<int:organization_id>/', views.organizacijaOglas, name='organizacijaOglas'),

    path('inbox/', views.inbox),
    path('chat/', include('chat.urls')),
   

    path('users/',include('users.urls')),

    path('', RedirectView.as_view(url='/oglasi/', permanent=True)),
    path('oglasi/', include('oglasi.urls')),  


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_Doniraj/faza5/Doniraj/chat/urls.py
from django.urls import path
from .views import *
#Autor: Stasa Zujkovic 2021/0321
app_name = 'chat'

urlpatterns = [
    path('', chat_view, name="home"),
    path('chat/<username>', get_or_create_chatroom, name="start-chat"),
    path('chatroom/<chatroom_name>', chat_view, name="chatroom"),
    
]

project_Doniraj/faza5/Doniraj/oglasi/urls.py
from django.urls import path
from . import views
#Autor: Lazar Krpovic 2021/0633
app_name = 'oglasi'

urlpatterns = [
    path('', views.pocetna , name="home"),
    path('oglas/<int:oglas_id>/', views.oglas, name='oglas'),
    path('fetch_oglases/', views.fetch_oglases, name='fetch_oglases'),
    path('postaviOglas/', views.postaviOglas, name = "postaviOglas"),
    path('search/', views.search, name='search'),
    path('delete_oglas/<int:oglas_id>/', views.deleteOglas, name = "deleteOglas"),
]

project_Doniraj/faza5/Doniraj/users/urls.py
#Autor: Matija Milic 2021/0088
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('registracija/',views.registracija, name = "registracija"),
    path('logovanje/',views.logovanje, name = "logovanje"),
    path('logout/',views.logout_view, name = "logout"),
    path('nalozi/',views.nalozi, name = "nalozi"),
    path('zahtevi/',views.zahtevi, name = "zahtevi"),
    path('zahtev/<int:id>/', views.zahtev, name='zahtev'),
    path('zahtev/<int:id>/approve/', views.approve_zahtev, name='approve_zahtev'),
    path('zahtev/<int:id>/reject/', views.reject_zahtev, name='reject_zahtev'),
    path('promenaLozinke/', views.promenaLozinke, name='promenaLozinke'),
    path('promenaSlike/', views.promenaSlike, name='promenaSlike'),
    path('delete_account/<int:user_id>/', views.delete_account, name='delete_account'),
    
    path('milica/<int:id>', views.milica, name = "milica"),

    path('zaboravljenaLozinka/', views.zaboravljenaLozinka, name = "zaboravljenaLozinka"),
    path('code_verify/', views.codeVerify, name='code_verify'),
    path('password_reset/', views.passwordReset, name='password_reset'),
]

project_Doniraj/faza5/Doniraj/users/forms.py
#Autor: Matija Milic 2021/0088
from urllib.error import URLError
from urllib.parse import urlparse
from urllib.request import urlopen
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from .models import User, Organization

#Forma za registraciju obicnog korisnika
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=255, help_text='Required. Add a valid email address.')

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2', )

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise forms.ValidationError("Email already exists")
        return email

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise forms.ValidationError("Username already exists")
        return username
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2
    
#Forma za registraciju ogranizacije
class OrganizationRegistrationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['name',  'address', 'pib', 'website', 'description', 'needs_description']
    def clean_website(self):
        website = self.cleaned_data.get('website')
        if website:
            parsed_url = urlparse(website)
            if not (parsed_url.scheme and parsed_url.netloc):
                raise forms.ValidationError("Enter a valid URL.")

            if not parsed_url.scheme:
                website = 'http://' + website

            try:
                
                with urlopen(website) as response:
                    pass  
            except URLError:
                raise forms.ValidationError("The URL does not seem to point to a valid website.")
        return website
    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

#Forma za prijavu
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('username')
    email = forms.EmailField(label="Email", max_length=255, help_text='Required. Add a valid email address.')
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    
    class Meta:
        fields = ['email', 'password'] 

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if email and password:
            user = authenticate(username=email, password=password)
            if user is None:
                raise forms.ValidationError("Invalid email or password.")
        return cleaned_data
    

#Forma za promenu profilne slike
class ProfilePictureForm(forms.ModelForm):
    clear_image = forms.BooleanField(required=False, initial=False, label='Clear current image')

    class Meta:
        model = User
        fields = ['image']

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        if self.cleaned_data.get('clear_image'):
            user.image = 'profile_pics/profil.png'
        user.save()
        return user

project_Doniraj/faza5/Doniraj/users/views.py
#Autor: Matija Milic 2021/0088
from django.conf import settings
from django.utils import timezone 
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import ProfilePictureForm, RegistrationForm, LoginForm, OrganizationRegistrationForm
from django.urls import reverse
from .models import User, Organization, Zahtev
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.db.models import Q
from oglasi.models import Oglas
# Create your views here.

def admin_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden("You are not authorized to view this page.")
        return view_func(request, *args, **kwargs)
    return _wrapped_view


def anonymous_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponse("You are already authenticated as " + request.user.email)
        return view_func(request, *args, **kwargs)
    return _wrapped_view


def login_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden("You are not authorized to view this page.")
        return view_func(request, *args, **kwargs)
    return _wrapped_view


@anonymous_required
def registracija(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse("You are already authenticated as " + user.email)

    context = {}

    if request.POST:
        registration_type = request.POST.get('registrationType')
        if registration_type == 'organization':
            org_form = OrganizationRegistrationForm(request.POST)
            user_form = RegistrationForm(request.POST)
            if org_form.is_valid() and user_form.is_valid():
                user = user_form.save(commit=False)
                user.is_organization = True
                user.save()
                organization = org_form.save()
                organization.user = user
                organization.accepted = False  
                organization.save()
                Zahtev.objects.create(
                    organization=organization,
                    time=timezone.now()
                )
                messages.success(request, "Your registration request has been submitted. You will receive an email notification once your request is processed.")
                return render(request, 'users/registracija.html', context)
            else:
                context['registration_form'] = user_form
                context['organization_form'] = org_form
        else:
            form = RegistrationForm(request.POST)
            if form.is_valid():
                form.save()
                email = form.cleaned_data.get('email').lower()
                raw_password = form.cleaned_data.get('password1')
                account = authenticate(email=email, password=raw_password)
                if account:
                    login(request, account)
                return redirect(reverse("oglasi:home"))
            else:
                context['registration_form'] = form
    else:
        context['registration_form'] = RegistrationForm()
        context['organization_form'] = OrganizationRegistrationForm()

    return render(request, 'users/registracija.html', context)


@anonymous_required
def logovanje(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse("You are already authenticated as " + user.email)

    context = {}
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                try:
                    organization = Organization.objects.get(user=user)
                    if organization and not organization.accepted:
                        context['login_error'] = "Your organization is not yet approved by the admin."
                    else:
                        login(request, user)
                        destination = kwargs.get("next")
                        if destination:
                            return redirect(destination)
                        return redirect(reverse("oglasi:home"))
                except Organization.DoesNotExist:
                    login(request, user)
                    destination = kwargs.get("next")
                    if destination:
                        return redirect(destination)
                    return redirect(reverse("oglasi:home"))
            else:
                context['login_error'] = "Invalid email or password"
        else:
            context['login_form'] = form
    else:
        context['login_form'] = LoginForm()

    return render(request, 'users/logovanje.html', context)

#izlistava zahteve
@admin_required
def zahtevi(request):
    zahtevi = Zahtev.objects.all().order_by('-time')  
    return render(request, 'users/zahtevi.html', {'zahtevi': zahtevi})


#prikazuje pojedinacan zahtev
@admin_required
def zahtev(request, id):
    zahtev = get_object_or_404(Zahtev, id=id)
    return render(request, 'users/zahtev.html', {'zahtev': zahtev})

#izlistava naloge (obicni korisnici, admini i prihvacene organizacije)
@admin_required
def nalozi(request):
    korisnici = User.objects.all()
    
    prihvacene_org = Organization.objects.filter(accepted=True)

    filtered_users = korisnici.filter(
        Q(organization__isnull=True) | Q(organization__in=prihvacene_org)
    )

    filtered_users = filtered_users.exclude(is_staff=True)
    
    return render(request, 'users/nalozi.html', {'korisnici': filtered_users})

@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("oglasi:home"))

#prihvatanje/odbijanje zahteva
@admin_required
def approve_zahtev(request, id):
    zahtev = get_object_or_404(Zahtev, id=id)
    organization = zahtev.organization
    organization.accepted = True
    organization.save()
    zahtev.delete()  

    subject = 'Vas zahtev je prihvacen'
    html_message = render_to_string('email/request_approved.html', {'organization': organization})
    plain_message = strip_tags(html_message)
    from_email = 'donirajaplikacija@gmail.com'
    to_email = organization.user.email
    send_mail(subject, plain_message, from_email, [to_email], html_message=html_message)

    return redirect('users:zahtevi')


@admin_required
def reject_zahtev(request, id):
    zahtev = get_object_or_404(Zahtev, id=id)
    organization = zahtev.organization
    zahtev.delete()

    subject = 'Vas zahtev je odbijen'
    html_message = render_to_string('email/request_rejected.html', {'organization': organization})
    plain_message = strip_tags(html_message)
    from_email = 'donirajaplikacija@gmail.com'
    to_email = organization.user.email
    send_mail(subject, plain_message, from_email, [to_email], html_message=html_message)
    organization.user.delete()
    organization.delete()
    return redirect('users:zahtevi')


@login_required
def promenaLozinke(request):
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  
            context['success_message'] = 'Vaša lozinka je uspešno promenjena!'
            context['redirect_time'] = 2  
            return render(request, 'users/promenaLozinke.html', context)
        else:
            context['error_message'] = 'Molimo ispravite greške ispod.'
    else:
        form = PasswordChangeForm(request.user)
    
    context['form'] = form
    return render(request, 'users/promenaLozinke.html', context)


#pocetak procesa zaboravljena lozinka: kod je generisan i poslat na email
@anonymous_required
def zaboravljenaLozinka(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        if email:
            user = User.objects.filter(email=email).first()
            if user:
                token_generator = default_token_generator
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = token_generator.make_token(user)
                code = f"{uid}-{token}"
                
                send_mail(
                    'Password Reset Code',
                    f'Your password reset code is: {code}',
                    settings.DEFAULT_FROM_EMAIL,
                    [email],
                    fail_silently=False,
                )

                request.session['password_reset_email'] = email
                request.session['password_reset_code'] = code
                
                return redirect('users:code_verify')
            else:
                return render(request, 'users/zaboravljenaLozinka.html', {'error': 'Invalid email', 'step': 1})
        else:
            return render(request, 'users/zaboravljenaLozinka.html', {'error': 'Email is required', 'step': 1})
    else:
        return render(request, 'users/zaboravljenaLozinka.html', {'step': 1})

project_Doniraj/faza5/Doniraj/users/templates/users/logovanje.html
<!--Autori: Matija Milic i Marija Stakic-->
{% extends 'layout.html' %}

{% block title %}
    Logovanje
{% endblock %}

{% block content %}
<div class=" d-flex justify-content-center">
  <form method = "post" class = "form-login">
    {% csrf_token %}
    <div class="col-auto marg" style="max-width: 310px;">
      <div class="input-group">
        <input type="text" class="form-control" id="emailLog" placeholder="Email" name= "email" required>
      </div>
    </div>
  </div>
  <div class=" d-flex justify-content-center">
    <div class="col-auto marg" style="max-width: 310px;">
      <div class="input-group">
        <input type="password" class="form-control" id="lozinkaLog" placeholder="Lozinka" name= "password" required>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-6 text-center ">
  <a href="{% url 'users:zaboravljenaLozinka'%}" class="zaboravljena link-secondary malaSlova"> Zaboravili ste lozinku?</a> 
  <br>
  <a href="{% url 'users:registracija' %}" class="link-danger">Nemate nalog? Registruj se</a>
    </div></div>
  <div class="row justify-content-center">
    <div class="col-6 text-center marg">
      <button type="submit" class="btn btn-danger logBtn">Uloguj se</button>
    </div>

    {% if login_error %}
    <div class="row justify-content-center">
        <div class="col-6 text-center marg">
            <div style="color: red;">
                {{ login_error }}
            </div>
        </div>
    </div>
    {% endif %}
  {% if login_form.non_field_errors %}
    <div class="row justify-content-center">
      <div class="col-6 text-center marg">
        <div style="color: red;">
          {% for error in login_form.non_field_errors %}
            {{ error }}
          {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}
  </form>
  </div>

{% endblock %}

project_Doniraj/faza5/Doniraj/users/templates/users/milica.html
<!--Autori: Matija Milic i Marija Stakic-->
{% extends 'layout.html' %}

{% block title %}
    Profil
{% endblock %}
{% block content %}
<div class="profil marg levo d-flex align-items-center">
  <div class="rounded-circle vecaProfilna me-3">
    <img src="{{ user.image.url }}" alt="profilna" class="img-fluid">
  </div>
  <h3 class="me-3">@{{ user.username }}</h3>
  {% if request.user != user %}
  <a href="{% url 'chat:start-chat' user.username %}" class="link-secondary d-flex align-items-center">
    <img src="/media/images/chat.png" alt="chat" width="30px" class="me-2">
    Kontaktiraj
  </a>
  {% endif %}
</div>


<div class="d-flex justify-content-end margDesno">
  {% if request.user == user %}
    <a href="/inbox" class="me-3 link-dark slovaVeca">
      <img src="/media/images/inbox.png" alt="inbox" width="35px" id = "inboxslika">
      Inbox
    </a>
  {% endif %}
</div>

<div class="container mt-4">
  <div class="row justify-content-start">  
    {% for oglas in oglasi %}
    <div class="col-md-4 mb-4">
      <div class="card same-height-card" style="width: 18rem;"> 
        <a href="{% url 'oglasi:oglas' oglas.id %}">
          <div class="text-center">
            <img src="{{ oglas.slika.url }}" class="card-img-top img-fluid" alt="{{ oglas.naziv }}">
          </div>
        </a>
        <div class="card-body text-center">
          <h5 class="card-title">{{ oglas.naziv }}</h5>
          <p class="card-text">{{ oglas.opis }}</p>
          {% if request.user == user or request.user.is_staff %}
          <button type="button" class="btn btn-light obrisi delete-button-oglas" data-oglas-id="{{ oglas.id }}">
            Obriši Oglas
          </button>
          
            
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<form method="post" id="delete-form" style="display: none;">
  {% csrf_token %}
</form>

<script>
  document.addEventListener('DOMContentLoaded', function() {
      document.querySelectorAll('.delete-button-oglas').forEach(function(button) {
          button.addEventListener('click', function() {
              if (confirm("Da li ste sigurni da želite da obrišete oglas?")) {
                  const oglasId = this.getAttribute('data-oglas-id');
                  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  
                  fetch(`/oglasi/delete_oglas/${oglasId}/`, {
                      method: 'POST',
                      headers: {
                          'X-CSRFToken': csrftoken,
                          'Content-Type': 'application/json'
                      }
                  })
                  .then(response => response.json())
                  .then(data => {
                      if (data.status === 'success') {
                          this.closest('.col-md-4').remove(); 
                          alert(data.message);
                      } else {
                          alert(data.message);
                      }
                  })
                  .catch(error => console.error('Error:', error));
              }
          });
      });
  });
  </script>

{% endblock %}

project_Doniraj/faza5/Doniraj/users/templates/users/nalozi.html
<!--Autori: Matija Milic i Marija Stakic-->
{% extends 'layout.html' %}

{% block title %}
    Nalozi
{% endblock %}
{% block content %}

<div class="container mt-4">
    <h2>Lista Naloga</h2>


    <div class="row mt-4 justify-content-center">
        {% for korisnik in korisnici %}
            <div class="col-md-4 mb-4">
                <div class="card" style="width: 18rem;">
                    <div class="text-center">
                        <a href="{% url 'users:milica' korisnik.id %}">
                            <img src="{{ korisnik.image.url }}" class="card-img-top rounded-circle vecaProfilna" alt="profil">
                        </a>
                        
                    </div>
                    <div class="card-body text-center">
                        <h5 class="card-title">@{{ korisnik.username }}</h5>
                        <button type="button" class="btn btn-light obrisi delete-button" data-user-id="{{ korisnik.id }}">
                            <img src="/media/images/iks.png" alt="iks" width="20px"> Obriši Nalog
                        </button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

</div>

<form method="post" id="delete-form" style="display: none;">
    {% csrf_token %}
</form>


<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('.delete-button').forEach(function(button) {
            button.addEventListener('click', function() {
                if (confirm("Da li ste sigurni da želite da obrišete nalog?")) {
                    const userId = this.getAttribute('data-user-id');
                    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    
                    fetch(`/users/delete_account/${userId}/`, {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': csrftoken,
                            'Content-Type': 'application/json'
                        }
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status === 'success') {
                            this.closest('.col-md-4').remove(); 
                            alert(data.message);
                        } else {
                            alert(data.message);
                        }
                    })
                    .catch(error => console.error('Error:', error));
                }
            });
        });
    });
    </script>

{% endblock %}

project_Doniraj/faza5/Doniraj/users/templates/users/promenaLozinke.html
<!--Autori: Matija Milic i Marija Stakic-->
{% extends 'layout.html' %}

{% block title %}
    Promena Lozinke
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3 mx-auto">
            <h2>Promena lozinke</h2>
            {% if success_message %}
                <div class="alert alert-success">
                    {{ success_message }}
                </div>
                <script>
                    setTimeout(function() {
                        {% if  request.user.is_staff %} window.location.href="{% url 'users:milica' request.user.id%}" class="nav-link link-secondary" id="profileDropdown"> 
                        {% elif request.user.is_organization%} window.location.href="/organizacijaProfil" class="nav-link link-secondary" id="profileDropdown"> 
                        {% else %} window.location.href="{% url 'users:milica' request.user.id%}" class="nav-link link-secondary" id="profileDropdown">   {%endif%}
                        }, {{ redirect_time }} * 1000); 
                </script>
            {% else %}
                {% if error_message %}
                    <div class="alert alert-danger">
                        {{ error_message }}
                    </div>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.old_password.label_tag }}
                        {{ form.old_password }}
                        {% for error in form.old_password.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        {{ form.new_password1.label_tag }}
                        {{ form.new_password1 }}
                        {% for error in form.new_password1.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        {{ form.new_password2.label_tag }}
                        {{ form.new_password2 }}
                        {% for error in form.new_password2.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn btn-danger" id="prihvati">Promeni</button>
                </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

project_Doniraj/faza5/Doniraj/users/templates/users/promenaSlike.html
<!--Autori: Matija Milic i Marija Stakic-->
{% extends 'layout.html' %}

{% block title %}
    Promena profilne
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Promena profilne slike</h2>
                </div>
                <div class="card-body">
                    {% if user.image %}
                        <div class="text-center mb-4">
                            <img src="{{ user.image.url }}" class="rounded-circle" alt="Current Profile Picture" width="150" height="150">
                        </div>
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            {{ form.image.label_tag }}
                            {{ form.image }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </form>
                    {% if messages %}
                        <ul class="messages mt-3">
                            {% for message in messages %}
                                <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project_Doniraj/faza5/Doniraj/users/templates/users/zahtev.html
<!--Autori: Matija Milic i Marija Stakic-->
{% extends 'layout.html' %}

{% block title %}
    Zahtev
{% endblock %}

{% block content %}

<div class="container mt-4">
    <h2>Informacije o Zahtevu</h2>

    <div class="card mt-4">
        <div class="card-body">
            <h5 class="card-title">Detalji Zahteva</h5>
            <p class="card-text">
                <strong>Ime Organizacije:</strong> {{ zahtev.organization.name }}<br>
                <strong>E-mail adresa:</strong> {{ zahtev.organization.user.email }}<br>
                <strong>Adresa:</strong> {{ zahtev.organization.address }}<br>
                <strong>Identifikacioni broj (PIB):</strong> {{ zahtev.organization.pib }}<br>
                {% if zahtev.organization.website %}
                <strong>Link sajta organizacije:</strong> 
                <a href="{{ zahtev.organization.website }}" class="link-danger">{{ zahtev.organization.website }}</a><br>
                {% endif %}
            </p>
            <div class="text-center">
                <form method="post" action="{% url 'users:approve_zahtev' zahtev.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success mr-2">Odobri</button>
                </form>
                <form method="post" action="{% url 'users:reject_zahtev' zahtev.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Odbaci</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

project_Doniraj/faza5/Doniraj/users/templates/users/zahtevi.html
<!--Autori: Matija Milic i Marija Stakic-->
{% extends 'layout.html' %}

{% block title %}
    Zahtevi
{% endblock %}

{% block content %}

<div class="container mt-4">
    <h2 class="mb-4">Lista Zahteva</h2>

    <ul class="list-group">
        {% for zahtev in zahtevi %}
        <a href="{% url 'users:zahtev' zahtev.id %}">
            <li class="list-group-item">
                <div class="font-weight-bold">{{ zahtev.organization.name }}</div>
                <small class="text-muted">{{ zahtev.time|date:"d. F Y." }}</small>
            </li>
        </a>
        {% endfor %}
    </ul>

</div>

{% endblock %}